name: kosaraju
version: 0.1.0.0
extra-source-files: []
author: Alex Dixon
github: dixonary/kosaraju
license: GPL-3

description: Please see the README on GitHub at <https://github.com/dixonary/kosaraju#readme>

executables:
  kosaraju:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kosaraju

library:
  source-dirs: src
tests:
  kosaraju-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kosaraju
    - hspec

copyright: 2019 Alex Dixon
maintainer: alexander.dixon@warwick.ac.uk
dependencies:
- vector
- base >= 4.7 && < 5
- sbv == 8.2
- containers
- mtl
- filepath
- megaparsec
- pretty-simple
- vass
- karp-miller
- text
- duvet
- silently
- async
- optparse-applicative


default-extensions:
- TypeSynonymInstances
- FlexibleInstances
- UnicodeSyntax
- RecordWildCards
- OverloadedStrings
- OverloadedLists
- QuasiQuotes
- LambdaCase
- MultiWayIf
- TupleSections
- DuplicateRecordFields
- BangPatterns
- GADTs
- RankNTypes